# -*- coding: utf-8 -*-
"""run.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m3i5XCcntHfpxN-FeOM8gmXNQGudqe6I
"""

import datetime
from flask import Flask
app = Flask(__name__)


@app.route('/')
def hello_world():
    return 'Hello world!'

@app.route('time')
def now_time():
  now_time = datetime.datetime.now().strftime('%H:%M:%S; %m-%d-%y')
  return now_time

app.run(host='0.0.0.0',
        port=8080,
        debug=True)